### PR TITLE
remove long forgotten taxonomies

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by cordoval** [comment]
ping @inspiran

**Comment by cordoval** [comment]
ping @iampersistent please, i would greatly appreciate it as I am working and this error keeps popping up and i think is very obvious

thanks

**Comment by inspiran** [comment]
Luis, taxonomy should stay here.   v/core has a dependency on v/taxonomy for that reason.   What is the error that you get?

**Comment by cordoval** [comment]
@inspiran i think the reason is that dependency did not get enforced then, checking ...

**Comment by cordoval** [comment]
@iampersistent @inspiran https://github.com/vespolina/core/pull/97/files

**Pull request closed without merging**
